### ISSUE TITLE
Configure Authentication/Users

### ISSUE THREAD

**Issue by ghandmann** [EventStore/eventstore-docker#73]
Is there a way to configure the default username/password via Environment/Configuration when using EventStore in a container?

The [documentation](https://eventstore.org/docs/server/command-line-arguments/index.html#authentication-options) is giving rather vague information about this.

I think this would be an important option to change the Admin-User (at least the password) instead of running with well-known default credentials. :)

**Comment by av8ta** [comment]
I was stuck with this too @ghandmann , you simply change the password in the dashboard ui on port 2113 under users :pray:

**Comment by ghandmann** [comment]
> I was stuck with this too @ghandmann , you simply change the password in the dashboard ui on port 2113 under users

Of course you can, i know. :)
But thats not an option in an auto-deployment. Anytime we redeploy the EventStore i have to think about this. And than it's only a matter of time when i forget about it and on some customer server the EventStore UI is running with default credential. Very bad. ;)

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. 

The issue has been moved to [EventStore#2649](https://github.com/EventStore/EventStore/issues/2649).

Thank you.
