### ISSUE TITLE
Entrypoint does not pass along command line arguments

### ISSUE THREAD

**Issue by kaancfidan** [EventStore/eventstore-docker#77]
Command line arguments are sometimes necessary when environment variables cannot be set for the container (e.g. current implementation of Gitlab CI job services). 

Even if there were no such use-cases, command line arguments not being handled is confusing and a feature degradation without a trade-off.

**To reproduce:**
- Create the container:
```bash
docker run -it --rm -p 2113:2113 -p 1113:1113 eventstore/eventstore --run-projections=all --start-standard-projections=true
```

- Browse to http://localhost:2113/web/index.html#/projections

**Expected behavior:**
All system projections should be **Running**.

**Actual behavior:**
All system projections are **Stopped**.

**Comment by arwinneil** [comment]
Hello,

This issue has been closed due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. 

The issue has been moved to [EventStore#2654](https://github.com/EventStore/EventStore/issues/2654).

Thank you.
